#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Run script with environment variables like SEARCHISKO_CB_PROVIDER_USERNAME etc.
source ${OPENSHIFT_DATA_DIR}/.searchiskoenv