sudo: false
language: java
cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

script:
  - mvn test

before_script:
  - mysql -e 'create database searchisko_test;'
  - export SEARCHISKO_TEST_CONNECTION_URL=jdbc:mysql://localhost/searchisko_test
  - export SEARCHISKO_TEST_USERNAME=travis
  - export SEARCHISKO_TEST_PASSWORD=

after_success:
  - mvn clean cobertura:cobertura coveralls:report

